name: Test

on:
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Diff
        run: |
          git diff main --name-only ${{ github.event.before }} ${{ github.event.after }} | grep pyproject.toml
